name: Elixir CI

on:
  push:


jobs:
  build:
    name: compile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      id: setup-elixir
      with:
        otp-version: '26.2.3'
        elixir-version: '1.18.0'
        install-hex: true
        install-rebar: true

    - name: Restore Hex and Mix cache
      uses: actions/cache@v4
      id: mix-cache
      with:
        path: |
          ~/.mix
          ~/.hex
        key: ${{ runner.os }}-mix-26.2.3-1.18.0-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-26.2.3-1.18.0-

    - name: Install dependencies
      run: mix deps.get

    - name: Upload compiled artifacts and deps
      uses: actions/upload-artifact@v4
      with:
        name: elixir-build-artifacts
        path: |
          _build/
          deps/
          mix.lock
        retention-days: 1
